import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/layout";
import { SwapBox } from "../components/swap";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Axelar Satellite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="grid grid-cols-2 h-full">
          <div></div>
          <div className="h-full pt-40">
            <SwapBox />
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
