import type { NextPage } from "next";
import Head from "next/head";
import { Layout, Navbar } from "../components/layout";
import { PageHeader, SwapBox } from "../components/swap";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Axelar Satellite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Navbar />
        <div className="grid h-full grid-cols-2 pt-48 justify-items-center">
          <div>
            <PageHeader />
          </div>
          <div className="h-full pt-16">
            <SwapBox />
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
