import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";

import { Layout } from "../components/layout";
import { PageHeader, SwapBox } from "../components/swap";
import { useSwapStore } from "../store";
import { SwapStatus } from "../utils/enums";

const Home: NextPage = () => {
  const { swapStatus } = useSwapStore((state) => state);
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    if (swapStatus !== SwapStatus.IDLE) videoRef.current?.play();
  }, [swapStatus]);

  return (
    <div>
      <Head>
        <title>Axelar Satellite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.svg" />
      </Head>

      <Layout>
        <video
          ref={videoRef}
          className="fixed top-0 left-0 object-cover w-screen h-screen aspect-video -z-10"
          muted
          loop
          id="myVideo"
        >
          <source src="/video/bg.webm" type="video/webm" />
        </video>
        <div className="z-10 h-full grid grid-cols-1 pt-[30vh] md:grid-cols-2 justify-items-stretch">
          <div>
            <PageHeader />
          </div>
          <div className="flex items-start justify-end">
            <SwapBox />
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
